# Generated by Django 3.2.18 on 2023-03-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_identification_tag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
