# Generated by Django 3.2.18 on 2023-03-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stages', '0002_stage_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
